import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react"
import { Providers } from "./provider"
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en">
      <body> 
        <Providers>
          <Header />
          {props.children}
        </Providers>
      </body>
    </html>
  );
}
